version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'go-server:${IMAGE_TAG:-1.0}'
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    ports:
      - "80"
    command: go-server -p 80 -tsl 1
