version: '3.0'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        encKey: ${ENC_KEY}
        encIV: ${ENC_IV}
    image: 'go-server:${IMAGE_TAG:-1.0}'
    container_name: go-server
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./data/ssl:/go/src/github.com/hiromaily/go-server/data/ssl
      - ./runner.conf:/go/src/github.com/hiromaily/go-server/runner.conf
      - ./cmd:/go/src/github.com/hiromaily/go-server/cmd
      - ./controller:/go/src/github.com/hiromaily/go-server/controller
      - ./libs:/go/src/github.com/hiromaily/go-server/libs
      - ./templates:/go/src/github.com/hiromaily/go-server/templates
      - ./statics:/go/src/github.com/hiromaily/go-server/statics
    stdin_open: true
    tty: true
    restart: always
    command: fresh -c /go/src/github.com/hiromaily/go-server/runner.conf

  prometheus:
    image: 'prom/prometheus'
    container_name: prometheus
    ports:
      - "${PROM_PORT:-9090}:9090"
    volumes:
      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

#  headless:
#    image: 'knqz/chrome-headless'
#    container_name: chrome-headless
#    ports:
#      - "${HEADLESS_PORT:-9222}:9222"
#
#  devtool:
#    build:
#      context: ./chrome_devtools/
#      dockerfile: Dockerfile
#    image: 'devtool:${IMAGE_TAG:-1.0}'
#    container_name: devtool
#    volumes:
#      #- ./data/images:/workspace/images
#      - ./chrome_devtools:/go/src/github.com/hiromaily/go-server/chrome_devtools
#    links:
#      - headless:chrome-headless
#      - web
#    depends_on:
#      - headless
#      - web
#    stdin_open: true
#    tty: true
#    command: bash
