version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        encKey: ${ENC_KEY}
        encIV: ${ENC_IV}
    image: 'go-server:${IMAGE_TAG:-1.0}'
    container_name: go-server
    environment:
      CGO_ENABLED: 0
      GOOS: linux
    ports:
      - "${API_PORT:-8080}:8080"
    volumes:
      - ./cmd:/go/src/github.com/hiromaily/go-server/cmd
      - ./data/ssl:/go/src/github.com/hiromaily/go-server/data/ssl
      - ./pkg:/go/src/github.com/hiromaily/go-server/pkg
      - ./web:/go/src/github.com/hiromaily/go-server/web
    stdin_open: true
    tty: true
    restart: always
    command: go-server -p 8080

#  prometheus:
#    image: 'prom/prometheus'
#    container_name: prometheus
#    ports:
#      - "${PROM_PORT:-9090}:9090"
#    volumes:
#      - ./data/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
